version: '3.8'

services:
  database:
    container_name: 'postgres'
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'test'
    ports:
      - '5432:5432'

volumes:
  postgres:
    driver: local
